version: "3.8"

services:
  postgres-db:
    image: postgres:16.3
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_DB: go_gopher_social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:

networks:
  default:
    driver: bridge
